public class matterTrustActDetailWrapper {
    @auraEnabled
    public string Id{get;set;}
    
    @auraEnabled
    public string transactioName{get;set;}
    
    @auraEnabled
    public decimal amount{get;set;}
    
    @auraEnabled
    public date transactioDate{get;set;}
    
    @auraEnabled
    public string accountId{get;set;}
    
    @auraEnabled
    public string accountName{get;set;}
    
    @auraEnabled
    public string trustCode{get;set;}
    
    @auraEnabled
    public string reference{get;set;}
    
    @auraEnabled
    public date cdTransactioDate{get;set;}
    
    @auraEnabled
    public Decimal checkNo{get;set;}
    
    
}